version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./log:/eKom/log  # Логи будут сохраняться в папке ./log на хосте
    depends_on:
          - mongo
    networks:
      - network

volumes:
  db_data:

networks:
  network:
    driver: bridge

