name: Docker Compose Test

on:
  push:
    branches:
      - master

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
    
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Check Docker version
        run: docker --version

      - name: Build and run Docker Compose
        run: |
          docker compose down --volumes --remove-orphans
          docker compose up -d --build

      - name: Verify running containers
        run: docker ps

      - name: Wait for services to start
        run: sleep 10

      - name: Test app
        run: |
          pip install --no-cache-dir -r requirements.txt
          pytest test/

      - name: Upload log folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: log-folder
          path: ./log

      - name: Clean up
        if: always()
        run: docker compose down --volumes --remove-orphans
