name: Docker Compose Test

on:
  push:
    branches:
      - master

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose version
        run: docker-compose --version

      - name: Build and run Docker Compose
        run: |
          docker-compose down --volumes --remove-orphans
          docker-compose up -d --build

      - name: Verify running containers
        run: docker ps

      - name: Wait for services to start
        run: sleep 10

      - name: Check container logs
        run: docker-compose logs

      - name: Test Flask app healthcheck
        run: |
          curl -X POST http://127.0.0.1:5000/clear_db || exit 1

      - name: Clean up
        if: always()
        run: docker-compose down --volumes --remove-orphans
